language: csharp
solution: Aluno.sln
install:
  - nuget restore Aluno.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Aluno.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Alunoteste/bin/Debug/Alunoteste.dll
